pointers:
	g++ pointers.cpp -o pointers.out

arrays:
	g++ arrays.cpp -o arrays.out

graph-enummap:
	g++ graph/enum_map.cpp -o graph-enummap.out

glfw_cb_context:
	g++ -std=c++11 -g -Wall -Wextra -Wfatal-errors -pedantic \
		-lglfw -lGLEW -lGL -lX11 -lpthread -lXrandr -lXi\
		glfw_cb_context.cpp -o glfw_cb_context.out

clean:
	rm -f *.out
