#! @file
#! @author Vsevolod Ivanov

CXX=g++
CXXFLAGS=-Wall -Wextra -Wfatal-errors -pedantic -g -lpthread

nonblocking:
	${CXX} ${CXXFLAGS} -std=c++11 nonblocking.cpp -o nonblocking.out

clean:
	rm -f *.out
